"""
Django settings for LinkedIn project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from LinkedIn.base import *

import dj_database_url

ENVIRONMENT = 'production'
DEBUG = True
ALLOWED_HOSTS = ['*']
DATABASES['default'] = dj_database_url.config(
    default='postgres://umrqrubxcyocqe:ccd3c1fb43c064e4f91e2580e327809c8c9fdeb1e71e517f4920cda84fc36a63@ec2-50-17-189-165.compute-1.amazonaws.com:5432/dd0l84gko9jdi6'
)